server:
  port: 8000

spring:
  application:
    name: apigateway-service
    activate:
      on-profile: local
  config:
    import: optional:configserver:http://localhost:30002

eureka:
  client:
    service-url:
      defaultZone: http://localhost:30000/eureka